// Expanded bilingual study layer. Book-derived facts are kept distinct from open-web context.
// Preparation cards are intentionally framed as studio/industrial preparation profiles where a safe home recipe is not appropriate.

export const pigmentEnhancements = {
  "yellow-ochre": {mmName:"အဝါရောင် Ochre",descriptionEN:"A natural earth pigment dominated by hydrated iron oxides and clay minerals. Its colour can move from yellow to red-brown when the iron hydroxide phase is dehydrated by heat.",descriptionMM:"Hydrated iron oxide နဲ့ clay mineral တွေပါဝင်တဲ့ သဘာဝမြေသား pigment ဖြစ်ပါတယ်။ အပူပေးတဲ့အခါ iron hydroxide အဆင့်ပြောင်းပြီး အဝါကနေ အနီညိုဘက်သို့ ပြောင်းနိုင်ပါတယ်။",properties:{opacity:"Opaque / semi-opaque",staining:"Low",lightfastness:"Excellent",granulation:"Often moderate",tinting:"Low–medium",oilAbsorption:"Moderate",dryingOil:"Fast–medium",texture:"Earthy / soft"},historyLongEN:"Ochres are among the oldest known colour materials. Iron-rich earths containing yellow goethite and related minerals were collected, ground and used long before modern pigment manufacture. Heating yellow iron earths could transform them toward red ochre, linking geology directly to one of the earliest controlled pigment processes.",historyLongMM:"Ochre များသည် လူသားတို့အသုံးပြုခဲ့သော အစောဆုံးအရောင်ပစ္စည်းများထဲမှ တစ်မျိုးဖြစ်ပါတယ်။ Goethite စတဲ့ အဝါရောင် iron mineral ပါဝင်တဲ့ မြေသားကို စုဆောင်း၊ ကြိတ်ပြီး အသုံးပြုခဲ့ကြပါတယ်။ အဝါ ochre ကို အပူပေးခြင်းဖြင့် red ochre ဘက်သို့ ပြောင်းနိုင်တာက geology နဲ့ pigment-making ကို တိုက်ရိုက်ချိတ်ပေးပါတယ်.",makingEN:"Wash/levigate the earth if a cleaner fraction is wanted, dry it, grind and sieve. For redder variants, controlled calcination can dehydrate goethite toward hematite. Small comparative test batches are preferable.",makingMM:"ပိုသန့်တဲ့ fraction လိုပါက မြေသားကို ရေဖြင့် levigate/wash လုပ်ပြီး ခြောက်အောင်ထား၊ ကြိတ်၊ sieve လုပ်ပါ။ အနီဘက်ပိုလိုပါက controlled calcination ဖြင့် goethite ကို hematite ဘက်သို့ ပြောင်းနိုင်ပါတယ်။ အရင်ဆုံး batch သေးသေးနဲ့ နှိုင်းယှဉ်စမ်းသပ်ပါ။",makingType:"Studio process"},
  "red-ochre": {mmName:"အနီရောင် Ochre",descriptionEN:"An iron-oxide earth, commonly associated with hematite, with clay and other geological material affecting hue and texture.",descriptionMM:"Hematite/iron oxide ပါဝင်မှုအများကြီးရှိတဲ့ မြေသား pigment ဖြစ်ပြီး clay နဲ့ geological impurities တွေက hue နဲ့ texture ကို သက်ရောက်စေပါတယ်။",properties:{opacity:"Opaque / semi-opaque",staining:"Low",lightfastness:"Excellent",granulation:"Moderate",tinting:"Medium",oilAbsorption:"Moderate",dryingOil:"Fast–medium",texture:"Earthy"},historyLongEN:"Red ochre has a very long archaeological record in painting, ritual and body decoration. Its red colour is associated with iron oxides such as hematite, and it could also be produced by heating yellow iron earths.",historyLongMM:"Red ochre ကို ပန်းချီ၊ အခမ်းအနားနဲ့ ကိုယ်ခန္ဓာအလှဆင်မှုတွေမှာ ရှေးအလွန်ကတည်းက အသုံးပြုခဲ့ပါတယ်။ အနီရောင်ဟာ hematite လို iron oxide တွေနဲ့ ဆက်စပ်ပြီး yellow iron earth ကို အပူပေးခြင်းကနေလည်း ရရှိနိုင်ပါတယ်။",makingEN:"Clean by washing/levigation, dry, grind and sieve. Calcined yellow ochre is a traditional route to warmer red iron-oxide earths.",makingMM:"Wash/levigation လုပ်ပြီး ခြောက်၊ ကြိတ်၊ sieve လုပ်နိုင်ပါတယ်။ Yellow ochre ကို calcination လုပ်ခြင်းကနေ နွေးထွေးတဲ့ red iron-oxide earth ရနိုင်ပါတယ်။",makingType:"Studio process"},
  "raw-sienna": {mmName:"Raw Sienna",properties:{opacity:"Transparent–semi-transparent",staining:"Low",lightfastness:"Excellent",granulation:"Low–moderate",tinting:"Low–medium",oilAbsorption:"Moderate",dryingOil:"Fast",texture:"Fine earthy"},historyLongEN:"Sienna is a natural iron earth historically associated with Italian earth deposits. Raw sienna contains hydrated iron compounds and accessory minerals; heating produces the related burnt sienna colour.",historyLongMM:"Sienna သည် အီတလီမြေသားသိုက်များနှင့် သမိုင်းကြောင်းအရ ဆက်စပ်တဲ့ natural iron earth တစ်မျိုးပါ။ Raw sienna မှာ hydrated iron compound တွေနဲ့ အခြား mineral တွေပါဝင်ပြီး အပူပေးရင် burnt sienna ဘက်သို့ ပြောင်းပါတယ်။",makingEN:"Select and wash/levigate the earth, dry and grind. Keep a raw portion as a control; calcine a separate portion to make burnt sienna.",makingMM:"သင့်တော်တဲ့ earth ကိုရွေးပြီး wash/levigate လုပ်၊ ခြောက်၊ ကြိတ်ပါ။ Raw sample တစ်ပိုင်းကို control အဖြစ်ထားပြီး ကျန်တစ်ပိုင်းကို calcine လုပ်ကာ burnt sienna ပြောင်းလဲမှုကို စမ်းနိုင်ပါတယ်။",makingType:"Studio process"},
  "raw-umber": {mmName:"Raw Umber",properties:{opacity:"Transparent–semi-transparent",staining:"Low",lightfastness:"Excellent",granulation:"Moderate",tinting:"Medium",oilAbsorption:"Moderate–high",dryingOil:"Fast",texture:"Earthy / slightly coarse"},historyLongEN:"Umber is a manganese-bearing iron earth. Its dark brown character comes from the combination of iron oxides, manganese oxides and associated minerals. Heating converts raw umber toward burnt umber.",historyLongMM:"Umber သည် manganese ပါဝင်တဲ့ iron earth ဖြစ်ပါတယ်။ Iron oxide၊ manganese oxide နဲ့ အခြား mineral တွေပေါင်းစပ်မှုကြောင့် အညိုနက်ရောင်ရပါတယ်။ Raw umber ကို အပူပေးရင် burnt umber ဘက်သို့ ပြောင်းပါတယ်။",makingEN:"Wash/levigate if desired, dry, grind and sieve. Calcine a portion separately to compare raw and burnt states.",makingMM:"လိုအပ်ရင် wash/levigate လုပ်ပြီး ခြောက်၊ ကြိတ်၊ sieve လုပ်ပါ။ Raw နဲ့ burnt state ကွာခြားချက်ကိုကြည့်ဖို့ portion တစ်ခုကို သီးခြား calcine လုပ်ပါ။",makingType:"Studio process"},
  "green-earth": {mmName:"Green Earth / Terre Verte",properties:{opacity:"Transparent–semi-transparent",staining:"Low",lightfastness:"Excellent",granulation:"Low–moderate",tinting:"Low",oilAbsorption:"Moderate",dryingOil:"Fast",texture:"Fine mineral"},historyLongEN:"Green earth refers to naturally occurring green iron-bearing minerals such as glauconite and celadonite. Historical artists used it as a restrained mineral green, especially in underpainting and flesh modelling.",historyLongMM:"Green earth ဆိုတာ glauconite၊ celadonite လို green iron-bearing mineral တွေကို ဆိုလိုပါတယ်။ သမိုင်းဝင်ပန်းချီတွေမှာ muted mineral green အဖြစ်၊ အထူးသဖြင့် underpainting နဲ့ flesh modelling တွေမှာ အသုံးများခဲ့ပါတယ်။",makingEN:"The preparation is primarily mineral selection, crushing, washing/levigation, drying and grading rather than chemical synthesis.",makingMM:"အဓိကအားဖြင့် mineral ကိုရွေး၊ ကြိတ်၊ wash/levigate၊ ခြောက်ပြီး particle grade ခွဲခြားတာဖြစ်ပြီး chemical synthesis မဟုတ်ပါ။",makingType:"Mineral preparation"},
  "blue-earth": {mmName:"Blue Earth / Vivianite",properties:{opacity:"Semi-transparent",staining:"Medium",lightfastness:"Variable",granulation:"Moderate",tinting:"Medium",oilAbsorption:"Variable",dryingOil:"Medium",texture:"Crystalline / earthy"},historyLongEN:"Vivianite is a hydrated iron phosphate that can appear pale or nearly colourless before oxidation develops a stronger blue. It is a less common historical blue earth and illustrates how oxidation can become part of colour formation.",historyLongMM:"Vivianite သည် hydrated iron phosphate ဖြစ်ပြီး oxidation မဖြစ်ခင် အရောင်ဖျော့သို့မဟုတ် အရောင်မထင်ရှားနိုင်ပါ။ Oxidation ဖြစ်လာတဲ့အခါ အပြာရောင်ပိုထင်ရှားလာပြီး oxidation ကိုယ်တိုင်က colour formation ရဲ့ အစိတ်အပိုင်းဖြစ်လာပါတယ်။",makingEN:"Prepare by careful mineral selection, gentle grinding and washing/levigation. Avoid assuming that every blue sample is chemically identical; document oxidation and source.",makingMM:"သတ္တုနမူနာကို သေချာရွေး၊ နူးညံ့စွာကြိတ်၊ wash/levigate လုပ်ပါ။ Blue sample တိုင်း chemical composition တူမယ်လို့ မယူဆဘဲ source နဲ့ oxidation အခြေအနေကို မှတ်တမ်းတင်ပါ။",makingType:"Mineral preparation"},
  "woad": {mmName:"Woad / ဝေါဒ်အပင်အရောင်",properties:{opacity:"Transparent–semi-transparent",staining:"High",lightfastness:"Good–variable",granulation:"Low",tinting:"High",oilAbsorption:"Not meaningful as dry dye pigment",dryingOil:"Binder dependent",texture:"Fine crystalline"},historyLongEN:"Woad (Isatis tinctoria) was a major European source of indigo colour. Its importance declined when indigo from other regions and later synthetic indigo became widely available. The pigment-making process depends on converting plant precursors into insoluble indigotin.",historyLongMM:"Woad (Isatis tinctoria) သည် ဥရောပမှာ indigo အရောင်ရဲ့ အရေးကြီးတဲ့ အရင်းမြစ်ဖြစ်ခဲ့ပါတယ်။ နောက်ပိုင်းမှာ အခြားဒေသက indigo နဲ့ synthetic indigo ရရှိလွယ်လာတာကြောင့် အရေးပါမှုလျော့လာပါတယ်။ Pigment-making မှာ plant precursor ကို insoluble indigotin အဖြစ် ပြောင်းဖို့လိုပါတယ်။",makingEN:"Extract the indigo precursor from leaves, alkalize and aerate/oxidize the liquor, collect the blue precipitate, wash, dry and gently grind. Yield varies strongly with leaf quality.",makingMM:"အရွက်ထဲက indigo precursor ကို ထုတ်ယူပြီး alkaline ဖြစ်အောင်လုပ်၊ လေထိတွေ့/oxidize လုပ်ကာ အပြာ precipitate ဖြစ်လာစေပါ။ ပြီးရင် စု၊ ဆေး၊ ခြောက်၊ နူးညံ့စွာကြိတ်ပါ။ အရွက်အရည်အသွေးပေါ်မူတည်ပြီး yield အများကြီးကွာနိုင်ပါတယ်။",makingType:"Book recipe / studio"},
  "weld": {mmName:"Weld Lake / Weld အဝါ Lake",properties:{opacity:"Transparent–semi-transparent",staining:"Medium",lightfastness:"Variable; alum lake can improve permanence",granulation:"Low",tinting:"Medium",oilAbsorption:"High",dryingOil:"Binder dependent",texture:"Fine lake"},historyLongEN:"Weld (Reseda luteola) was an important European yellow dye plant, especially in medieval and Renaissance colour practice. Its yellow flavonoid colourants could be precipitated onto an aluminium-containing substrate to make a lake pigment.",historyLongMM:"Weld (Reseda luteola) သည် medieval နဲ့ Renaissance ဥရောပအရောင်ယဉ်ကျေးမှုမှာ အရေးပါတဲ့ အဝါရောင်အပင်ဖြစ်ပါတယ်။ Flavonoid အဝါရောင် colourant ကို aluminium ပါတဲ့ substrate ပေါ် precipitate လုပ်ပြီး lake pigment ပြုလုပ်နိုင်ပါတယ်။",makingEN:"Hot-water extract the plant, strain, combine with alum, then add carbonate gradually to precipitate an aluminium hydroxide lake. Filter, wash until clear, dry and grind.",makingMM:"အပင်ကို ရေနွေးနဲ့ extract လုပ်၊ စစ်ပြီး alum နဲ့ပေါင်းပါ။ Carbonate ကို တဖြည်းဖြည်းထည့်ကာ aluminium hydroxide lake ဖြစ်အောင် precipitate လုပ်ပါ။ Filter၊ ရေကြည်လာသည်အထိ wash၊ ခြောက်ပြီး ကြိတ်ပါ။",makingType:"Book recipe / studio"},
  "madder": {mmName:"Madder / မက်ဒါအမြစ်",properties:{opacity:"Transparent",staining:"High",lightfastness:"Variable",granulation:"Low",tinting:"High",oilAbsorption:"High",dryingOil:"Slow",texture:"Fine lake"},historyLongEN:"Madder root became one of the major historical sources of red lake colour. Its anthraquinone colourants could be extracted and fixed onto a mineral substrate. The history of madder lakes is closely tied to changing extraction and laking techniques.",historyLongMM:"Madder root သည် သမိုင်းဝင် red lake အရောင်ရဲ့ အရေးကြီးတဲ့ အရင်းမြစ်တစ်ခုပါ။ Anthraquinone colourant တွေကို extract လုပ်ပြီး mineral substrate ပေါ်မှာ fix လုပ်နိုင်ပါတယ်။ Madder lake သမိုင်းဟာ extraction နဲ့ laking နည်းလမ်းတိုးတက်မှုတွေနဲ့ နီးကပ်စွာ ဆက်စပ်ပါတယ်။",makingEN:"Extract madder below boiling temperature, then use alum and carbonate chemistry to precipitate the colourant as a lake. Wash thoroughly, dry completely and grind. Excess heat can push the result toward a duller red-brown.",makingMM:"Madder ကို boiling မဖြစ်အောင် အပူထိန်းပြီး extract လုပ်ပါ။ Alum နဲ့ carbonate chemistry သုံးပြီး colourant ကို lake အဖြစ် precipitate လုပ်ပါ။ သေချာ wash၊ အပြည့်အဝခြောက်ပြီး ကြိတ်ပါ။ အပူလွန်ရင် အရောင်က ညိုနီဘက်ကို မဲသွားနိုင်ပါတယ်။",makingType:"Book recipe / studio"},
  "lapis": {mmName:"Lapis Lazuli / Natural Ultramarine",properties:{opacity:"Semi-transparent",staining:"Low",lightfastness:"Excellent",granulation:"Moderate–high",tinting:"Medium",oilAbsorption:"High",dryingOil:"Medium",texture:"Crystalline / granular"},historyLongEN:"Natural ultramarine came from lapis lazuli, historically sourced from Central Asian deposits. Because the blue lazurite fraction is embedded in a complex rock containing calcite, pyrite and other minerals, producing a strong blue involved careful crushing, separation and purification. Its scarcity made it a prestigious historical colour.",historyLongMM:"Natural ultramarine ကို lapis lazuli ကနေ ရရှိပြီး သမိုင်းမှာ Central Asia ဒေသသတ္တုသိုက်တွေနဲ့ ဆက်စပ်ပါတယ်။ အပြာ lazurite fraction က calcite၊ pyrite စတဲ့ mineral တွေနဲ့ ရောနေတဲ့အတွက် ကြိတ်ခြင်း၊ ခွဲခြားခြင်း၊ သန့်စင်ခြင်းတွေ လိုအပ်ပါတယ်။ ရှားပါးတာကြောင့် သမိုင်းဝင်တန်ဖိုးမြင့်တဲ့ အရောင်ဖြစ်လာပါတယ်။",makingEN:"Crush, grind and separate the blue lazurite-rich fraction from the host rock using staged washing/levigation and careful grading. The historic process is labour intensive; avoid inhaling mineral dust.",makingMM:"Raw lapis ကို crush၊ grind လုပ်ပြီး host rock ထဲက lazurite-rich blue fraction ကို washing/levigation နဲ့ အဆင့်လိုက်ခွဲပါ။ သမိုင်းဝင်နည်းက အလုပ်များပြီး mineral dust မရှူမိအောင် အထူးဂရုစိုက်ပါ။",makingType:"Mineral processing"},
  "azurite": {mmName:"Azurite / အဇူရိုက်",properties:{opacity:"Semi-transparent",staining:"Medium",lightfastness:"Good",granulation:"Moderate–high",tinting:"Medium–high",oilAbsorption:"Moderate",dryingOil:"Medium",texture:"Crystalline"},historyLongEN:"Azurite is a basic copper carbonate found in oxidized zones of copper deposits, often alongside malachite. It has a long history as a blue mineral pigment. Particle size matters: coarse particles can retain stronger mineral brilliance, while excessive grinding can change the visual character.",historyLongMM:"Azurite သည် copper deposit တွေရဲ့ oxidized zone မှာ တွေ့ရတဲ့ basic copper carbonate ဖြစ်ပြီး malachite နဲ့အတူ တွေ့ရတတ်ပါတယ်။ အပြာရောင် mineral pigment အဖြစ် သမိုင်းရှည်အသုံးပြုခဲ့ပါတယ်။ Particle size က အရေးကြီးပြီး ကြမ်းတဲ့ particle က mineral brilliance ကို ထိန်းနိုင်သလို အလွန်ကြိတ်လွန်းရင် visual character ပြောင်းနိုင်ပါတယ်။",makingEN:"Crush the mineral, dampen with water to control dust, separate softer impurities by washing/levigation, allow the heavier blue fraction to settle, then dry and grade. The handbook describes repeated washing for difficult specimens.",makingMM:"Mineral ကို crush လုပ်ပြီး dust ထိန်းဖို့ ရေဖြင့် စိုစွတ်ထားပါ။ ပျော့တဲ့ impurity တွေကို washing/levigation နဲ့ ခွဲပြီး အလေးပိုတဲ့ အပြာ fraction ကို အောက်မှာ settle ဖြစ်စေပါ။ ပြီးရင် ခြောက်ပြီး grade ခွဲပါ။ မသန့်တဲ့ specimen တွေမှာ အကြိမ်များစွာ wash လုပ်ရနိုင်ပါတယ်။",makingType:"Book recipe / studio"},
  "malachite": {mmName:"Malachite / မလာခိုက်",properties:{opacity:"Semi-transparent",staining:"Medium",lightfastness:"Excellent",granulation:"High",tinting:"Medium",oilAbsorption:"Moderate",dryingOil:"Medium",texture:"Crystalline / granular"},historyLongEN:"Malachite is a basic copper carbonate and one of the oldest important mineral greens. Historical painters used it for foliage and other green passages. Particle size strongly affects its green: finer material becomes lighter and more subdued.",historyLongMM:"Malachite သည် basic copper carbonate ဖြစ်ပြီး ရှေးဟောင်းအရေးပါတဲ့ mineral green တစ်မျိုးပါ။ သစ်ရွက်စိမ်းနဲ့ အခြား green passage တွေမှာ သုံးခဲ့ကြပါတယ်။ Particle size က အရောင်ကို အလွန်သက်ရောက်ပြီး ပိုကြိတ်သေးလေလေ အစိမ်းဖျော့ပြီး subdued ဖြစ်လာနိုင်ပါတယ်။",makingEN:"Crush the mineral, wash and levigate to remove softer impurities, then dry and grade. Avoid excessive grinding if a strong mineral green is desired.",makingMM:"Mineral ကို crush၊ wash၊ levigate လုပ်ပြီး ပျော့တဲ့ impurity တွေဖယ်ပါ။ ပြီးရင် ခြောက်ပြီး particle grade ခွဲပါ။ Mineral green ပြင်းပြင်းလိုရင် အလွန်အကျွံမကြိတ်ပါနဲ့။",makingType:"Book recipe / studio"},
  "verditer": {mmName:"Verditer / ကြေးနီကာဗိုနိတ် Pigment",properties:{opacity:"Semi-transparent",staining:"Medium",lightfastness:"Variable",granulation:"Moderate",tinting:"Medium",oilAbsorption:"Moderate",dryingOil:"Medium",texture:"Crystalline"},historyLongEN:"Verditer describes historic copper-carbonate pigments made artificially from copper compounds. Blue and green verditers developed alongside the use of azurite and malachite and became important in European painting materials.",historyLongMM:"Verditer ဆိုတာ copper compound တွေကနေ artificial ပြုလုပ်တဲ့ copper-carbonate pigment မျိုးစုကို ဆိုလိုပါတယ်။ Azurite နဲ့ malachite အသုံးပြုမှုနဲ့အတူ blue/green verditer တွေ တိုးတက်လာပြီး ဥရောပပန်းချီပစ္စည်းသမိုင်းမှာ အရေးပါလာပါတယ်။",makingEN:"Historical recipes use copper salts and controlled precipitation to form basic copper carbonate. The exact hue depends on chemistry and conditions; treat historical recipes as controlled material studies.",makingMM:"သမိုင်းဝင် recipe တွေမှာ copper salt တွေကို သုံးပြီး controlled precipitation နဲ့ basic copper carbonate ဖွဲ့စည်းပါတယ်။ Chemistry နဲ့ process condition ပေါ်မူတည်ပြီး hue ကွာနိုင်တာကြောင့် historical recipe ကို controlled material study အဖြစ်ပဲ သဘောထားပါ။",makingType:"Historical chemical process"},
  "cochineal": {mmName:"Cochineal Lake / ကိုချီနီးလ်",properties:{opacity:"Transparent",staining:"High",lightfastness:"Low–variable",granulation:"Low",tinting:"High",oilAbsorption:"High",dryingOil:"Slow",texture:"Fine lake"},historyLongEN:"Cochineal is an insect-derived red colourant associated with Mesoamerica and later global trade. After the Spanish conquest, cochineal became a major imported colour source in Europe. Its soluble colourant can be converted into a carmine-type lake.",historyLongMM:"Cochineal သည် Mesoamerica နဲ့ ဆက်စပ်တဲ့ ပိုးကရတဲ့ အနီရောင် colourant ဖြစ်ပြီး နောက်ပိုင်း ကမ္ဘာလုံးဆိုင်ရာကုန်သွယ်မှုထဲ ဝင်လာပါတယ်။ Spanish conquest နောက်ပိုင်း ဥရောပကို တင်သွင်းတဲ့ အရေးကြီးအရောင်အရင်းမြစ်ဖြစ်လာပါတယ်။ Soluble colourant ကို carmine-type lake အဖြစ် ပြောင်းနိုင်ပါတယ်။",makingEN:"Extract the colourant in water, combine with alum, then precipitate a carmine lake with an alkaline carbonate phase. Filter, wash, dry and grind. The colour and permanence depend strongly on substrate and pH.",makingMM:"Colourant ကို ရေထဲ extract လုပ်၊ alum နဲ့ပေါင်းပြီး alkaline carbonate phase နဲ့ carmine lake အဖြစ် precipitate လုပ်ပါ။ Filter၊ wash၊ ခြောက်၊ ကြိတ်ပါ။ အရောင်နဲ့ permanence က substrate နဲ့ pH ပေါ် အလွန်မူတည်ပါတယ်။",makingType:"Lake preparation"},
  "oak-gall": {mmName:"Oak Gall Ink / သပိတ်သီးမှင်",properties:{opacity:"Transparent–semi-transparent",staining:"High",lightfastness:"Good–variable",granulation:"Low",tinting:"High",oilAbsorption:"Not intended for oil",dryingOil:"Not intended for oil",texture:"Fluid ink"},historyLongEN:"Oak-gall ink is a historic iron-tannin writing medium. Gall tissues contain tannins that react with iron salts to form a dark iron-tannin complex. It is especially important in manuscript and archival history.",historyLongMM:"Oak gall ink သည် tannin နဲ့ iron ဓာတုတုံ့ပြန်မှုကို အသုံးပြုတဲ့ သမိုင်းဝင်စာရေးမှင်ပါ။ Oak gall ထဲက tannin က iron salt နဲ့ တုံ့ပြန်ပြီး အနက်ရောင် iron-tannin complex ဖြစ်စေပါတယ်။ Manuscript နဲ့ archival history မှာ အလွန်အရေးပါပါတယ်။",makingEN:"Extract tannins from crushed galls, prepare an iron-containing solution, combine carefully and allow the dark complex to develop. The recipe is an ink process rather than a conventional insoluble pigment preparation.",makingMM:"ကြိတ်ထားတဲ့ oak gall ကနေ tannin extract လုပ်၊ iron ပါတဲ့ solution ပြင်ပြီး သတိထားပေါင်းပါ။ အနက်ရောင် complex ဖြစ်လာအောင် စောင့်ပါ။ ဒါက ပုံမှန် insoluble pigment ပြုလုပ်နည်းထက် ink-making process ဖြစ်ပါတယ်။",makingType:"Ink preparation"},
  "verdigris": {mmName:"Verdigris / ကြေးစိမ်း",properties:{opacity:"Transparent–semi-transparent",staining:"High",lightfastness:"Variable / unstable",granulation:"Low",tinting:"High",oilAbsorption:"Moderate",dryingOil:"Fast–medium in suitable oil systems",texture:"Fine crystalline"},historyLongEN:"Verdigris is a family of copper corrosion products, historically produced by exposing copper to acidic vapours such as vinegar. It was valued for a strong blue-green but is chemically reactive and can contribute to deterioration in paint films.",historyLongMM:"Verdigris သည် copper ကို vinegar လို acidic vapour တွေနဲ့ ထိတွေ့စေပြီး ဖြစ်ပေါ်လာတဲ့ copper corrosion product မျိုးစုပါ။ အပြာစိမ်းပြင်းတာကြောင့် သမိုင်းဝင်တန်ဖိုးရှိပေမယ့် chemical reactivity မြင့်ပြီး paint film ပျက်စီးမှုကို ဖြစ်စေနိုင်ပါတယ်။",makingEN:"Historical preparation uses controlled corrosion of copper in an acidic/moist environment, followed by scraping, drying and processing the corrosion product. Because copper salts are reactive, this should be treated as a specialist study rather than a casual home recipe.",makingMM:"သမိုင်းဝင်ပြုလုပ်နည်းမှာ copper ကို acidic/moist environment ထဲမှာ controlled corrosion ဖြစ်စေပြီး corrosion product ကို စု၊ ခြောက်၊ process လုပ်ပါတယ်။ Copper salt တွေက reactive ဖြစ်လို့ casual home recipe မဟုတ်ဘဲ specialist material study အဖြစ်ပဲ လုပ်သင့်ပါတယ်။",makingType:"Historical specialist process"}
};

const chartProfiles = {
  "Alizarin crimson":["Alizarin crimson","Alizarin (synthetic analogue of madder colourants) was developed from anthraquinone chemistry in the 19th century and transformed the economics of red lake colour.","Alizarin crimson သည် madder colourant ကို synthetic chemistry နဲ့ အစားထိုးနိုင်အောင် ၁၉ ရာစုမှာ ဖွံ့ဖြိုးလာတဲ့ anthraquinone အခြေပြု အနီရောင်ပါ။","Industrial synthesis from anthraquinone intermediates; not a home recipe."],
  "Cadmium red":["Cadmium red","Cadmium red belongs to cadmium sulfide/selenide pigment chemistry and became important for its strong, opaque warm red and durability.","Cadmium red သည် cadmium sulfide/selenide chemistry အုပ်စုဝင်ဖြစ်ပြီး အနီရောင်ပြင်း၊ opaque ဖြစ်မှုနဲ့ durability ကြောင့် အရေးပါလာပါတယ်။","Specialist inorganic manufacture; cadmium compounds require controlled industrial handling."],
  "Quinacridone red":["Quinacridone red","Quinacridone pigments emerged from modern organic pigment chemistry and are valued for transparent, highly lightfast colour.","Quinacridone pigment များသည် ခေတ်သစ် organic pigment chemistry ကနေ ဖွံ့ဖြိုးလာပြီး transparent ဖြစ်ကာ lightfastness ကောင်းပါတယ်။","Specialist organic synthesis and controlled crystallization; not a studio recipe."],
  "Naphthol red":["Naphthol red","Naphthol reds are synthetic azo-family pigments developed for strong, economical red colour.","Naphthol red သည် azo-family synthetic pigment ဖြစ်ပြီး အရောင်ပြင်းပြီး စီးပွားရေးအရ အသုံးများတဲ့ red pigment အုပ်စုပါ။","Industrial azo coupling and pigment finishing; specialist manufacture."],
  "Perylene red":["Perylene red","Perylene pigments are modern high-performance organic pigments with strong colour and good stability.","Perylene pigment များသည် ခေတ်သစ် high-performance organic pigment ဖြစ်ပြီး အရောင်ပြင်းနဲ့ stability ကောင်းပါတယ်။","Specialist organic synthesis and crystallization."],
  "Pyrrole red":["Pyrrole red","Pyrrole pigments are modern organic reds noted for strong, clean colour and high permanence.","Pyrrole red သည် modern organic red pigment ဖြစ်ပြီး clean colour နဲ့ permanence ကောင်းပါတယ်။","Specialist organic synthesis; no home formulation."],
  "Dioxazine purple":["Dioxazine purple","Dioxazine pigments are high-performance synthetic organic violets with strong staining and transparency.","Dioxazine purple သည် synthetic organic violet ဖြစ်ပြီး staining နဲ့ transparency မြင့်ပါတယ်။","Specialist organic synthesis and finishing."],
  "Quinacridone violet / Quinacridone magenta":["Quinacridone violet / magenta","Quinacridone violet and magenta are modern organic pigments whose crystalline form strongly influences colour and transparency.","Quinacridone violet/magenta သည် crystal form က colour နဲ့ transparency ကို သက်ရောက်စေတဲ့ modern organic pigment များပါ။","Specialist synthesis plus controlled polymorph/crystal processing."],
  "Ultramarine blue":["Ultramarine blue","Synthetic ultramarine was developed in the early 19th century as a more affordable alternative to natural lapis ultramarine.","Synthetic ultramarine blue ကို ၁၉ ရာစုအစောပိုင်းမှာ natural lapis ultramarine ထက် ဈေးသက်သာတဲ့ အစားထိုးအရောင်အဖြစ် ဖွံ့ဖြိုးခဲ့ပါတယ်။","Industrial calcination of silica/alumina-containing materials with sulfur and sodium-bearing components; not a casual home process."],
  "Phthalo blue":["Phthalo blue","Phthalocyanine blue is a powerful synthetic organic pigment family developed in the 20th century, valued for extreme tinting strength and permanence.","Phthalo blue (phthalocyanine blue) သည် ၂၀ ရာစုမှာ ဖွံ့ဖြိုးလာတဲ့ synthetic organic pigment ဖြစ်ပြီး tinting strength နဲ့ permanence အလွန်ကောင်းပါတယ်။","Specialist copper-phthalocyanine synthesis and pigment finishing."],
  "Manganese blue":["Manganese blue","Manganese blue is a historical inorganic blue associated with manganese chemistry; commercial artist versions have varied by formulation.","Manganese blue သည် manganese chemistry နဲ့ ဆက်စပ်တဲ့ inorganic blue ဖြစ်ပြီး commercial formulation တွေ ကွာနိုင်ပါတယ်။","Specialist inorganic manufacture; manganese compounds require controlled handling."],
  "Cobalt blue":["Cobalt blue","Cobalt blue is a stable inorganic pigment associated with cobalt aluminate spinel chemistry and 19th-century synthetic colour development.","Cobalt blue သည် cobalt aluminate spinel chemistry နဲ့ ဆက်စပ်တဲ့ stable inorganic pigment ဖြစ်ပြီး ၁၉ ရာစု synthetic colour development နဲ့ ဆက်စပ်ပါတယ်။","High-temperature ceramic/inorganic synthesis; specialist process."],
  "Cerulean blue":["Cerulean blue","Cerulean blue is a cobalt-based inorganic pigment valued for a softer, slightly greenish blue and good permanence.","Cerulean blue သည် cobalt အခြေပြု inorganic pigment ဖြစ်ပြီး အစိမ်းဘက်နည်းနည်းပါသော အပြာနဲ့ permanence ကောင်းတာကြောင့် အသုံးများပါတယ်။","Specialist high-temperature inorganic manufacture."],
  "Phthalo green":["Phthalo green","Phthalocyanine green is made by modifying the phthalocyanine pigment system, giving extremely strong transparent green.","Phthalo green သည် phthalocyanine system ကို ပြုပြင်ဖန်တီးထားပြီး transparent ဖြစ်ကာ အစိမ်းရောင်အင်အားအလွန်ပြင်းပါတယ်။","Specialist halogenated phthalocyanine manufacture."],
  "Cobalt green":["Cobalt green","Cobalt green is a cobalt-containing inorganic green with relatively restrained tinting strength and good stability.","Cobalt green သည် cobalt ပါဝင်တဲ့ inorganic green ဖြစ်ပြီး tinting strength ပိုထိန်းထားကာ stability ကောင်းပါတယ်။","Specialist high-temperature inorganic manufacture."],
  "Terre verte":["Terre verte","Terre verte refers to natural green-earth minerals such as glauconite and celadonite rather than a single synthetic chemical.","Terre verte သည် chemical တစ်မျိုးတည်းမဟုတ်ဘဲ glauconite/celadonite လို natural green-earth mineral များကို ရည်ညွှန်းပါတယ်။","Mineral selection, washing, levigation, drying and grading."],
  "Viridian":["Viridian","Viridian is a hydrated chromium(III) oxide green, valued for transparent cool green and permanence.","Viridian သည် hydrated chromium(III) oxide green ဖြစ်ပြီး အေးမြတဲ့ transparent green နဲ့ permanence ကောင်းပါတယ်။","Specialist chromium-oxide hydration/manufacture; chromium compounds require controlled handling."],
  "Aureolin":["Aureolin","Aureolin is a historical yellow artist pigment name associated with cobalt-based chemistry; formulations vary and modern substitutes exist.","Aureolin သည် cobalt အခြေပြု chemistry နဲ့ ဆက်စပ်တဲ့ သမိုင်းဝင် yellow pigment အမည်ဖြစ်ပြီး formulation ကွာနိုင်ပါတယ်။","Specialist chemical manufacture; use verified artist-grade material rather than attempting synthesis."],
  "Hansa yellow / Lemon yellow":["Hansa yellow / Lemon yellow","Hansa yellows are modern organic pigments selected for clean bright yellow and useful mixing behaviour.","Hansa yellow သည် သန့်ရှင်းတောက်ပတဲ့ yellow နဲ့ mixing အတွက် အသုံးဝင်တဲ့ modern organic pigment အုပ်စုပါ။","Industrial azo pigment synthesis and finishing."],
  "Nickel azo yellow":["Nickel azo yellow","Nickel azo yellows are transparent modern organic pigments with earthy/brownish yellow character.","Nickel azo yellow သည် transparent modern organic pigment ဖြစ်ပြီး အညိုဘက်ဆန်တဲ့ yellow character ရှိပါတယ်။","Specialist azo pigment synthesis with nickel complex chemistry."],
  "Cadmium yellow":["Cadmium yellow","Cadmium yellow is a classic opaque inorganic yellow known for strong warm colour and permanence, but cadmium toxicity requires careful handling.","Cadmium yellow သည် warm yellow ပြင်းပြီး opaque၊ permanent ဖြစ်တဲ့ classic inorganic pigment ဖြစ်ပေမယ့် cadmium toxicity ကြောင့် သေချာကိုင်တွယ်ရပါတယ်။","Specialist cadmium sulfide/selenide manufacture; do not attempt at home."],
  "Burnt sienna":["Burnt sienna","Burnt sienna is produced by heating a sienna earth, driving off water from hydrated iron minerals and shifting the colour warmer/redder.","Burnt sienna သည် sienna earth ကို အပူပေးပြီး hydrated iron mineral ရဲ့ ရေဓာတ်ပြောင်းလဲစေကာ အနီနွေးဘက်သို့ ရွှေ့ထားတဲ့ earth pigment ပါ။","Controlled calcination of raw sienna, followed by cooling, grinding and grading."],
  "Burnt umber":["Burnt umber","Burnt umber is the heat-transformed form of raw umber, generally darker and warmer because of iron mineral changes during calcination.","Burnt umber သည် raw umber ကို အပူပေးပြောင်းလဲထားတာဖြစ်ပြီး calcination ကြောင့် ပိုနက်ပြီး ပိုနွေးတဲ့ brown ဖြစ်လာပါတယ်။","Controlled calcination, cooling, grinding and grading."],
  "Raw sienna":["Raw sienna","Raw sienna is a natural iron earth with a yellow-brown/orange-brown character.","Raw sienna သည် yellow-brown/orange-brown character ရှိတဲ့ natural iron earth ပါ။","Select, wash/levigate, dry, grind and sieve the earth."],
  "Raw umber":["Raw umber","Raw umber is a manganese-bearing iron earth with a dark neutral brown character.","Raw umber သည် manganese ပါတဲ့ iron earth ဖြစ်ပြီး dark neutral brown character ရှိပါတယ်။","Select, wash/levigate, dry, grind and sieve; reserve a portion for comparison with burnt umber."],
  "Yellow ochre":["Yellow ochre","Yellow ochre is a hydrated iron earth; heating can transform it toward red ochre.","Yellow ochre သည် hydrated iron earth ဖြစ်ပြီး အပူပေးရင် red ochre ဘက်သို့ ပြောင်းနိုင်ပါတယ်။","Wash/levigate, dry, grind and sieve; calcine a separate portion if a redder variant is wanted."],
  "Ivory or bone black":["Ivory or bone black","Bone black is a carbon-rich black made from calcined animal bone and contains mineral ash as well as carbon.","Bone black သည် animal bone ကို calcination လုပ်ရာက ရလာတဲ့ carbon-rich black ဖြစ်ပြီး carbon နဲ့ mineral ash နှစ်မျိုးလုံးပါဝင်ပါတယ်။","Controlled calcination of bone is a specialist process; use commercially prepared artist pigment for practical work."],
  "Mars black":["Mars black","Mars black is a synthetic iron-oxide black, valued for strong opacity and stability.","Mars black သည် synthetic iron-oxide black ဖြစ်ပြီး opacity နဲ့ stability ကောင်းပါတယ်။","Specialist precipitation/calcination of iron compounds; use prepared artist pigment for studio practice."],
  "Titanium white":["Titanium white","Titanium dioxide is the dominant modern opaque white pigment because its high refractive index produces strong light scattering and hiding power.","Titanium dioxide သည် refractive index မြင့်လို့ အလင်း scattering အလွန်ကောင်းပြီး opacity/hiding power မြင့်တဲ့ modern white pigment ဖြစ်ပါတယ်။","Industrial sulfate or chloride process followed by controlled particle-size/crystal finishing."],
  "Zinc white / Chinese white":["Zinc white / Chinese white","Zinc oxide is a white inorganic pigment with less hiding power than titanium dioxide and a more transparent character in many media.","Zinc oxide သည် inorganic white pigment ဖြစ်ပြီး titanium dioxide ထက် hiding power နည်းကာ medium အများစုမှာ ပို transparent ဖြစ်ပါတယ်။","Industrial zinc-oxide manufacture by oxidation or related controlled processes; use prepared artist pigment." ]
};

for (const [name, [title, en, mm, making]] of Object.entries(chartProfiles)) {
  const key = name;
  pigmentEnhancements[`chart:${key}`] = {
    mmName: title,
    descriptionEN: en,
    descriptionMM: mm,
    properties: {opacity:"See quality chart",staining:"See quality chart",lightfastness:"See quality chart",granulation:"Medium dependent",tinting:"Pigment dependent",oilAbsorption:"Formulation dependent",dryingOil:"Binder dependent",texture:"Particle-dependent"},
    historyLongEN: en + " Its development belongs to the broader history of artist pigment chemistry and changing manufacturing technology.",
    historyLongMM: mm + " ၎င်း၏ဖွံ့ဖြိုးမှုသည် ပန်းချီ pigment chemistry နဲ့ manufacturing technology တိုးတက်လာမှုသမိုင်းနဲ့ ဆက်စပ်ပါတယ်။",
    makingEN: making,
    makingMM: making + " သီးခြား studio synthesis ထက် verified artist-grade pigment ကို အသုံးပြုခြင်းက ပိုသင့်တော်ပါတယ်။",
    makingType: making.includes("Industrial") || making.includes("Specialist") ? "Industrial / specialist preparation" : "Material preparation"
  };
}

export const mediumScience = [
  {title:"Binder is not just glue",mmTitle:"Binder ဆိုတာ ကော်သက်သက်မဟုတ်ပါ",en:"A binder surrounds and holds pigment particles, controls wetting and adhesion, and becomes part of the final optical film. Changing the binder can change gloss, saturation, transparency, flow and drying.",mm:"Binder က pigment particle တွေကို ချိတ်ထားရုံမက wetting၊ adhesion၊ gloss၊ saturation၊ transparency၊ flow နဲ့ drying ကိုပါ သက်ရောက်စေပါတယ်။ Binder ပြောင်းရင် pigment တူပေမယ့် paint ရဲ့ အမြင်နဲ့ အလုပ်လုပ်ပုံ ပြောင်းနိုင်ပါတယ်။",lab:"Compare one pigment in gum arabic, acrylic polymer and oil on identical swatches."},
  {title:"Watercolour: gum arabic + water",mmTitle:"Watercolour: gum arabic + ရေ",en:"Watercolour keeps pigment dispersed in a water-soluble gum system. Water controls flow and apparent value; humectants keep the paint workable. Surface tension and particle size can promote or suppress granulation.",mm:"Watercolour မှာ pigment ကို gum arabic ရဲ့ water-soluble system ထဲမှာ disperse လုပ်ထားပါတယ်။ ရေက flow နဲ့ အရောင်ဖျော့ထင်ပေါ်မှုကို ထိန်းပြီး humectant က paint ကို ပြန်စိုလို့ရအောင် ကူညီပါတယ်။ Surface tension နဲ့ particle size က granulation ကို သက်ရောက်စေပါတယ်။",lab:"Make a two-pigment wash and compare wet-to-dry value shift, staining and granulation."},
  {title:"Acrylic: polymer dispersion",mmTitle:"Acrylic: polymer dispersion",en:"Acrylic paint suspends pigment in an acrylic polymer dispersion. As water evaporates, polymer particles coalesce into a continuous film. This can lock pigment in place quickly and change the appearance between wet and dry states.",mm:"Acrylic paint မှာ pigment ကို acrylic polymer dispersion ထဲမှာ ထားပါတယ်။ ရေငွေ့ပျံသွားတဲ့အခါ polymer particle တွေ coalesce ဖြစ်ပြီး film တစ်ခု ဖြစ်လာပါတယ်။ ဒါကြောင့် wet/dry colour ကွာခြားမှုနဲ့ layer တည်ဆောက်မှု အလျင်မြန်မှုကို သက်ရောက်စေပါတယ်။",lab:"Compare one transparent and one opaque pigment in thin glaze, mid-body and thick stroke."},
  {title:"Oil: drying oil oxidation",mmTitle:"Oil: drying oil oxidation",en:"Oil paint dries mainly through oxidation and cross-linking of drying oils rather than simple evaporation. Pigment surface area, oil absorption and the specific oil influence drying rate, gloss and film structure.",mm:"Oil paint က ရေလို အငွေ့ပျံပြီး ခြောက်တာမဟုတ်ဘဲ drying oil ရဲ့ oxidation နဲ့ cross-linking က အဓိကဖြစ်ပါတယ်။ Pigment ရဲ့ surface area၊ oil absorption နဲ့ အသုံးပြုတဲ့ oil အမျိုးအစားက drying rate၊ gloss နဲ့ film structure ကို သက်ရောက်စေပါတယ်။",lab:"Record touch-dry time for a small controlled swatch rather than assuming a pigment has one fixed drying time."},
  {title:"Particle size & light",mmTitle:"Particle size နဲ့ အလင်း",en:"Smaller particles can increase surface area and affect dispersion; larger or irregular particles can granulate. Optical behaviour also depends on refractive index, crystal form and the difference between pigment and binder.",mm:"Particle သေးလေလေ surface area တိုးနိုင်ပြီး dispersion အပေါ် သက်ရောက်ပါတယ်။ Particle ကြီး/ပုံသဏ္ဌာန်မညီတာတွေက granulation ဖြစ်စေနိုင်ပါတယ်။ Refractive index၊ crystal form နဲ့ pigment/binder ကြား index ကွာခြားမှုကလည်း optical behaviour ကို သတ်မှတ်ပါတယ်။",lab:"Grind one sample finer than another and compare opacity, hue, texture and settling."}
];

export const extendedTheory = [
  ["Color Terms & Properties","Hue identifies the colour family; value describes lightness/darkness; chroma describes intensity relative to neutral; saturation is often used for perceived purity/intensity. Keep these dimensions separate from pigment chemistry.","Hue က အရောင်မိသားစုကို၊ Value က အလင်း/အမှောင်ကို၊ Chroma က neutral နဲ့ နှိုင်းယှဉ်တဲ့ အရောင်အင်အားကို ဖော်ပြပါတယ်။ Saturation ကိုလည်း အရောင်ရဲ့ purity/intensity အဓိပ္ပာယ်နဲ့ အသုံးများပါတယ်။ ဒီ terms တွေကို pigment chemistry နဲ့ မရောသင့်ပါ။"],
  ["Color, Light & Shadow","Colour is perceived through light. A pigment is not the same thing as a light colour: pigments selectively absorb and scatter wavelengths while illumination changes what reaches the eye.","အရောင်ကို အလင်းကနေတစ်ဆင့် မြင်ရပါတယ်။ Pigment က light colour ကိုယ်တိုင်မဟုတ်ပါဘူး။ Pigment က wavelength တချို့ကို စုပ်ယူပြီး တချို့ကို scatter/reflect လုပ်တာကြောင့် မြင်ရတဲ့အရောင် ဖြစ်လာတာပါ။ အလင်းအခြေအနေပြောင်းရင် မြင်ရတဲ့ colour လည်း ပြောင်းနိုင်ပါတယ်။"],
  ["Color Relativity","A colour can appear warmer, cooler, lighter, darker or more saturated depending on surrounding colours. Therefore a swatch should be judged in context, not alone.","အရောင်တစ်ခုရဲ့ နွေး/အေး၊ ဖျော့/နက်၊ တောက်/မှိုင်း ဖြစ်ပုံက အနီးဝန်းကျင်အရောင်တွေပေါ် မူတည်ပြီး ပြောင်းထင်နိုင်ပါတယ်။ ဒါကြောင့် swatch ကို တစ်ရောင်တည်းကြည့်တာထက် context ထဲမှာ စစ်ဆေးသင့်ပါတယ်။"],
  ["Color Psychology","Artists can use learned associations, cultural references and physiological responses to build mood, but colour meaning is not universal. Context and culture matter.","အရောင်ကို mood ဖန်တီးရာမှာ လူမှုယဉ်ကျေးမှုဆိုင်ရာ association၊ အတွေ့အကြုံနဲ့ visual response တွေကို အသုံးချနိုင်ပါတယ်။ ဒါပေမယ့် အရောင်အဓိပ္ပာယ်ဟာ လူတိုင်းအတွက် တစ်မျိုးတည်းမဟုတ်ဘဲ context နဲ့ culture ပေါ် မူတည်ပါတယ်။"],
  ["Color & Mood","Warm/cool balance, chroma, value range, contrast and repetition can influence how energetic, quiet, tense or calm a painting feels.","Warm/cool balance၊ chroma၊ value range၊ contrast နဲ့ repetition တွေက ပန်းချီရဲ့ energetic၊ quiet၊ tense၊ calm စတဲ့ ခံစားချက်ကို ပြောင်းလဲစေနိုင်ပါတယ်။"],
  ["Color & Composition","Use value hierarchy first, then hue/chroma/temperature accents. A small saturated note can carry more visual weight than a large muted area.","Composition မှာ အရင်ဆုံး value hierarchy ကို တည်ဆောက်ပြီးမှ hue/chroma/temperature accent တွေ ထည့်သင့်ပါတယ်။ Saturated colour သေးသေးတစ်စက်က muted area ကြီးတစ်ခုထက် visual weight ပိုရနိုင်ပါတယ်။"],
  ["Infusing Color","When a reference is dull, preserve the value structure and deliberately alter hue, temperature or chroma to create a new colour interpretation.","Reference ပုံရဲ့ value structure ကို ထိန်းထားပြီး hue၊ temperature သို့မဟုတ် chroma ကို ရည်ရွယ်ချက်ရှိရှိ ပြောင်းသုံးခြင်းဖြင့် မူရင်းထက် ပိုစိတ်ဝင်စားစရာကောင်းတဲ့ colour interpretation ဖန်တီးနိုင်ပါတယ်။"],
  ["Tint / Tone / Shade","Tint = a hue lightened with white; shade = a hue darkened toward black; tone = a hue reduced or softened toward a neutral grey. These are paint-mixing concepts, not RGB/CMYK formulas.","Tint ဆိုတာ hue ကို white နဲ့ဖျော့ထားတာ၊ Shade ဆိုတာ black ဘက်သို့ နက်စေထားတာ၊ Tone ဆိုတာ neutral grey ဘက်သို့ လျော့/မှိုင်းစေထားတာပါ။ ဒါတွေက ပန်းချီဆေးရောစပ်မှုဆိုင်ရာ concept ဖြစ်ပြီး RGB/CMYK formula မဟုတ်ပါ။"],
  ["Natural / Grey / Neutral","Neutrals are not simply ‘no colour’. A grey can lean warm, cool, green, violet, blue or brown depending on its mixture and context.","Neutral ဆိုတာ အရောင်လုံးဝမရှိတာလို့ မဆိုလိုပါဘူး။ Grey တစ်ရောင်မှာ warm၊ cool၊ green၊ violet၊ blue၊ brown ဘက်သို့ bias ရှိနိုင်ပြီး mixture နဲ့ context က အဲဒီ bias ကို ဆုံးဖြတ်ပါတယ်။"],
  ["RGB vs CMYK vs Paint","RGB is an additive light model and CMYK is a subtractive printing model. Artist pigment mixing is physical subtractive/absorptive behaviour and cannot be treated as a direct RGB/CMYK recipe.","RGB က additive light model ဖြစ်ပြီး CMYK က subtractive printing model ဖြစ်ပါတယ်။ Artist pigment mixing က physical absorption/scattering ပေါ် မူတည်တာဖြစ်လို့ RGB/CMYK recipe ကို တိုက်ရိုက် paint mixing recipe အဖြစ် မယူသင့်ပါ။"]
];

export const historyExpanded = [
  {date:"PREHISTORY · tens of thousands of years ago",titleEN:"Earth, charcoal, bone and mineral colour",titleMM:"သမိုင်းမတင်မီ — မြေသား၊ charcoal၊ အရိုးနဲ့ သတ္တုအရောင်",en:"Early painting used locally available ochres, iron earths, charcoal, blackened bone and white mineral materials. These materials established the basic pattern of pigment practice: collect, grind, mix with a binding substance and apply to a surface.",mm:"အစောပိုင်းပန်းချီတွေမှာ ရရှိလွယ်တဲ့ ochre၊ iron earth၊ charcoal၊ burnt bone နဲ့ white mineral တွေကို သုံးခဲ့ကြပါတယ်။ Collect → grind → binder နဲ့ပေါင်း → surface ပေါ်အသုံးပြု ဆိုတဲ့ pigment practice ရဲ့ အခြေခံပုံစံကို ဒီကာလကတည်းက တွေ့ရပါတယ်။"},
  {date:"c. 4th millennium BCE",titleEN:"Egyptian Blue",titleMM:"ခန့်မှန်း BCE 4th millennium — Egyptian Blue",en:"Egyptian Blue is one of the earliest known deliberately manufactured synthetic inorganic pigments. CPMA describes a process involving sand, copper-bearing material and a sodium source heated at high temperature to form a calcium-copper-silicate pigment.",mm:"Egyptian Blue သည် လူသားတို့ ရည်ရွယ်ချက်ရှိရှိ ထုတ်လုပ်ခဲ့တဲ့ အစောဆုံး synthetic inorganic pigment များထဲက တစ်မျိုးပါ။ CPMA အရ sand၊ copper ပါဝင်တဲ့ material နဲ့ sodium source ကို အပူမြင့်ပေးပြီး calcium-copper-silicate pigment ဖန်တီးခဲ့ပါတယ်။"},
  {date:"ANCIENT WORLD",titleEN:"Ochres, cinnabar, orpiment, lapis and copper minerals",titleMM:"ရှေးဟောင်းကမ္ဘာ — Ochre၊ cinnabar၊ orpiment၊ lapis နဲ့ copper mineral",en:"Mineral pigments diversified. Natural ochres, cinnabar, orpiment, lapis lazuli, azurite and malachite entered different artistic traditions. Trade routes became as important as local geology for prestigious colours such as lapis.",mm:"Mineral pigment မျိုးစုံ တိုးလာပါတယ်။ Ochre၊ cinnabar၊ orpiment၊ lapis lazuli၊ azurite၊ malachite စတာတွေဟာ မတူညီတဲ့ အနုပညာယဉ်ကျေးမှုတွေထဲ ဝင်လာပါတယ်။ Lapis လို တန်ဖိုးမြင့်အရောင်တွေအတွက် local geology ထက် trade route ကပါ အရေးကြီးလာပါတယ်။"},
  {date:"4th century BCE → Roman period",titleEN:"Azurite and malachite in copper-rich regions",titleMM:"BCE 4th century မှ Roman ခေတ် — Azurite နဲ့ Malachite",en:"Copper-carbonate minerals became established blue and green artist materials. Historical sources and modern pigment studies show that particle size and preparation influenced their visual quality.",mm:"Copper-carbonate mineral တွေဟာ အပြာနဲ့အစိမ်းရောင် artist material အဖြစ် အရေးပါလာပါတယ်။ သမိုင်းဝင် source တွေနဲ့ modern pigment study တွေအရ particle size နဲ့ preparation က အရောင်အရည်အသွေးကို သက်ရောက်စေပါတယ်။"},
  {date:"MEDIEVAL EUROPE",titleEN:"Lakes, earths and specialist colour practice",titleMM:"အလယ်ခေတ်ဥရောပ — Lake၊ earth နဲ့ အထူးပြုအရောင်ဖော်စပ်မှု",en:"Artists and workshops increasingly worked with prepared colour materials. Lake pigments converted soluble dyes into insoluble colour, while earth pigments and mineral greens remained essential. Woad, weld and madder supported textile and artist colour cultures.",mm:"Artist workshop တွေမှာ ပြင်ဆင်ပြီးသား colour material တွေ ပိုမိုအသုံးများလာပါတယ်။ Lake pigment က soluble dye ကို insoluble colour အဖြစ်ပြောင်းပေးပြီး earth pigment နဲ့ mineral green တွေလည်း အရေးကြီးနေဆဲပါ။ Woad၊ weld၊ madder တို့က textile နဲ့ artist colour culture နှစ်ခုလုံးကို ထောက်ပံ့ခဲ့ပါတယ်။"},
  {date:"15th–16th centuries",titleEN:"Oil painting expands pigment possibilities",titleMM:"၁၅–၁၆ ရာစု — Oil painting နဲ့ pigment အသုံးချမှု တိုးချဲ့ခြင်း",en:"Drying oils such as linseed and walnut became major painting binders in Europe. The medium allowed transparent glazing, richer modelling and new relationships between pigment particle, binder and light.",mm:"Linseed oil၊ walnut oil စတဲ့ drying oil တွေဟာ ဥရောပပန်းချီမှာ အရေးပါတဲ့ binder တွေဖြစ်လာပါတယ်။ Oil medium ကြောင့် transparent glaze၊ rich modelling နဲ့ pigment–binder–light ဆက်နွယ်မှုအသစ်တွေ ပေါ်လာပါတယ်။"},
  {date:"16th century",titleEN:"Cochineal enters European colour trade",titleMM:"၁၆ ရာစု — Cochineal ဥရောပအရောင်ကုန်သွယ်မှုထဲ ဝင်လာခြင်း",en:"After the Spanish conquest of Mexico, cochineal became a major imported red colourant. Historical pigment research places early European references to cochineal lakes in the mid-16th century.",mm:"Mexico ကို Spanish conquest လုပ်ပြီးနောက် cochineal သည် ဥရောပသို့ တင်သွင်းတဲ့ အရေးကြီး red colourant ဖြစ်လာပါတယ်။ သမိုင်းဝင် pigment research အရ cochineal lake ကို ဥရောပ source တွေမှာ ၁၆ ရာစုအလယ်ပိုင်းက စတွေ့ရပါတယ်။"},
  {date:"1704 · early 18th century",titleEN:"Prussian Blue",titleMM:"၁၇၀၄ ဝန်းကျင် — Prussian Blue",en:"Prussian Blue became a landmark synthetic blue made through chemical reaction rather than mineral extraction. It helped demonstrate that strong artist colours could emerge from laboratory chemistry.",mm:"Prussian Blue သည် mineral ကနေ တူးယူတာမဟုတ်ဘဲ chemical reaction နဲ့ ပြုလုပ်တဲ့ landmark synthetic blue ဖြစ်လာပါတယ်။ Laboratory chemistry ကနေ artist အတွက် ပြင်းထန်တဲ့ အရောင်တွေ ထုတ်လုပ်နိုင်ကြောင်း ပြသပေးခဲ့ပါတယ်။"},
  {date:"18th century",titleEN:"Verditer, chrome colours and expanding manufacture",titleMM:"၁၈ ရာစု — Verditer၊ chrome colour နဲ့ ထုတ်လုပ်မှုတိုးတက်ခြင်း",en:"Synthetic and semi-synthetic colour processes multiplied. Copper verditers and chrome-based colours expanded the range of manufactured colour, while concerns about permanence and toxicity became increasingly important.",mm:"Synthetic နဲ့ semi-synthetic colour process တွေ တိုးလာပါတယ်။ Copper verditer နဲ့ chrome-based colour တွေက manufactured colour range ကို ချဲ့ထွင်ပေးခဲ့ပေမယ့် permanence နဲ့ toxicity ဆိုင်ရာ ပြဿနာတွေကလည်း ပိုအရေးကြီးလာပါတယ်။"},
  {date:"19th century",titleEN:"Cobalt, cadmium, synthetic ultramarine and modern chemistry",titleMM:"၁၉ ရာစု — Cobalt၊ cadmium၊ synthetic ultramarine နဲ့ modern chemistry",en:"The industrial chemistry of pigments accelerated. Synthetic ultramarine offered a cheaper alternative to natural lapis; cobalt and cadmium colours supplied strong stable hues; alizarin chemistry transformed red lakes.",mm:"Pigment industrial chemistry အလွန်မြန်မြန် တိုးတက်လာပါတယ်။ Synthetic ultramarine က natural lapis ကို ဈေးသက်သာစွာ အစားထိုးနိုင်ခဲ့ပြီး cobalt/cadmium colour တွေက stable hue တွေ ပေးခဲ့ပါတယ်။ Alizarin chemistry က red lake သမိုင်းကိုလည်း ပြောင်းလဲစေပါတယ်။"},
  {date:"20th century",titleEN:"Titanium white, phthalocyanines and high-performance pigments",titleMM:"၂၀ ရာစု — Titanium white၊ phthalocyanine နဲ့ high-performance pigment",en:"Titanium dioxide became the dominant modern white because of its strong scattering and opacity. Phthalocyanine blue and green introduced extremely strong, stable transparent colour; quinacridone and other modern organic families broadened the palette.",mm:"Titanium dioxide သည် scattering နဲ့ opacity အလွန်ကောင်းတာကြောင့် modern white ရဲ့ အဓိက pigment ဖြစ်လာပါတယ်။ Phthalocyanine blue/green က transparent ဖြစ်ပြီး အရောင်အင်အားနဲ့ stability အလွန်ကောင်းတဲ့ pigment တွေ ဖြစ်လာသလို quinacridone စတဲ့ modern organic family တွေလည်း palette ကို ချဲ့ပေးပါတယ်။"},
  {date:"21st century",titleEN:"Material awareness and the return to making",titleMM:"၂၁ ရာစု — Material awareness နဲ့ pigment-making ပြန်လည်စိတ်ဝင်စားလာခြင်း",en:"Artists now work across historical minerals, plant and animal lakes, synthetic pigments and waste-stream materials. The renewed interest is not simply nostalgia: provenance, toxicity, sustainability, particle behaviour and material knowledge are again part of colour practice.",mm:"ယနေ့ artist တွေက historical mineral၊ plant/animal lake၊ synthetic pigment နဲ့ waste-stream material တွေကို အတူတကွ အသုံးချနေကြပါတယ်။ ဒါဟာ အတိတ်ကို ပြန်လည်လွမ်းဆွတ်တာတင်မဟုတ်ဘဲ provenance၊ toxicity၊ sustainability၊ particle behaviour နဲ့ material knowledge ကို colour practice ထဲ ပြန်ထည့်သွင်းလာတာပါ။"}
];
